[package]
name = "found-it-again-rs2"
license = "Apache-2.0"
description = "First crate to publish"
version = "0.1.20"
edition = "2024"

[lib]
name = "found_it_again"

[[bin]]
name = "again"
path = "bin/again.rs"

[dependencies]
